AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation template to create an AWS Cloud9 development environment.

Resources:
  MyCloud9Environment1  :
    Type: 'AWS::Cloud9::EnvironmentEC2'
    Properties:
      Name: MyCloud9Environment
      Description: 'My Cloud9 Development Environment'
      InstanceType: 't2.medium'  # The EC2 instance type for the Cloud9 environment
      SubnetId: 'subnet-0d2ce5ad92f967994'  # Replace with the Subnet ID where you want to launch the EC2 instance
      AutomaticStopTimeMinutes: 30  # The number of minutes before the environment automatically stops if there's no activity
      ConnectionType: 'CONNECT_SSM'  # The type of connection to the instance (CONNECT_SSM allows using AWS Systems Manager Session Manager)
      # OwnerArn: 'arn:aws:iam::123456789012:user/MyUser'  # Replace with the ARN of the IAM user who should own the environment
      InstanceName: 'glenn'  # The key pair name for the EC2 instance
      AdditionalSecurityGroups:
        - 'sg-07284fc3936d77353'  # The ID of the security group to associate with the EC2 instance
      ImageId: 'ami-0a3d620ff8acd9dd7'  # The ID of the AMI to use for the EC2 instance
      VolumeSize: 15  # The size of the root volume in GB for the EC2 instance
    
  MyElasticIP:
    Type: 'AWS::EC2::EIP'

  ElasticIpAssociation:
    Type: 'AWS::EC2::EIPAssociation'
    Properties:
      InstanceId: !GetAtt MyCloud9Environment1.InstanceId
      EIP: !Ref MyElasticIP

Outputs:
  Cloud9EnvironmentId:
    Value: !Ref MyCloud9Environment
    Description: The ID of the AWS Cloud9 environment.
