AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy 5 EC2 instances with Elastic IP from predefined AMI and instance type

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-0a3d620ff8acd9dd7
      KeyName: 'glenn'
      SubnetId: subnet-0d2ce5ad92f967994
      SecurityGroupIds:
        - sg-07284fc3936d77353
      BlockDeviceMappings:
        - DeviceName: /dev/sda1
          Ebs:
            VolumeSize: 15
            VolumeType: gp2

  EIP:
    Type: AWS::EC2::EIP

  EIPAssociation1:
    Type: AWS::EC2::EIPAssociation
    Properties:
      InstanceId: !Ref EC2Instance1
      EIP: !Ref EIP

Outputs:
  EC2Instance1Id:
    Description: The ID of EC2 instance 1
    Value: !Ref EC2Instance1



  # EC2Instance2:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance3:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance4:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance5:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2
