AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy 5 EC2 instances from predefined AMI and instance type

Resources:
  EC2Instance1:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium
      ImageId: ami-043e0fe9035570bd2
      KeyName: 'glenn'
      SubnetId: subnet-0d2ce5ad92f967994
      SecurityGroupIds:
        - sg-07284fc3936d77353
      BlockDeviceMappings:
        - DeviceName: /dev/xvda
          Ebs:
            VolumeSize: 15
            VolumeType: gp2

  # EC2Instance2:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance3:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance4:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2

  # EC2Instance5:
  #   Type: AWS::EC2::Instance
  #   Properties:
  #     InstanceType: t2.medium
  #     ImageId: ami-043e0fe9035570bd2
  #     KeyName: 'glenn'
  #     SubnetId: subnet-0d2ce5ad92f967994
  #     SecurityGroupIds:
  #       - sg-07284fc3936d77353
  #     BlockDeviceMappings:
  #       - DeviceName: /dev/xvda
  #         Ebs:
  #           VolumeSize: 15
  #           VolumeType: gp2
