AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFormation Template to deploy multiple EC2 instances from a specific AMI

Parameters:
  NumberOfInstances:
    Description: Number of EC2 instances to create
    Type: Number
    Default: 1
    MinValue: 1
    MaxValue: 10
    ConstraintDescription: Must be a number between 1 and 10.

Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.medium  # Predefined instance type
      ImageId: ami-12345678  # Replace 'ami-12345678' with your desired AMI ID
      # You can add more properties here as needed, such as security groups, key pairs, etc.

Outputs:
  InstanceId:
    Description: The IDs of the created EC2 instances
    Value: !Join [",", !GetAtt EC2Instance.*.InstanceId]
    Export:
      Name: !Sub "${AWS::StackName}-InstanceIds"
