Resources:
  Cloud9OfficialEnvironmentTekweb:
    Type: AWS::Cloud9::EnvironmentEC2
    Properties:
      AutomaticStopTimeMinutes: 30
      ConnectionType: CONNECT_SSH
      Description: My Cloud9 Environment
      ImageId: ubuntu-22.04-x86_64
      InstanceType: t2.medium
      Name: TekwebIDE
      SubnetId: subnet-0f8a0dde6aba59f88
  
Outputs:
  Cloud9OutputID:
    Value: !Ref Cloud9OfficialEnvironmentTekweb
    Export:
      Name: !Sub "${AWS::StackName}-Cloud9ID"